Repository redhat-cne/cloud-event-proxy, pull requests merged in 2021-11, with the labels that each got.

#77 Master event and metrics
  cmd/main.go
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/stats/stats.go
Labels: approved

#78 Fixed metrics name typo
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm

#80 Revendor with go 1.17
  .github/workflows/main.yaml
  go.mod
  go.sum
  vendor/github.com/Azure/go-amqp/go.mod
  vendor/github.com/Azure/go-amqp/go.sum
  vendor/github.com/andybalholm/brotli/go.mod
  vendor/github.com/andybalholm/brotli/go.sum
  vendor/github.com/cespare/xxhash/v2/.travis.yml
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/go.mod
  vendor/github.com/cespare/xxhash/v2/go.sum
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/github.com/cloudevents/sdk-go/protocol/amqp/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/protocol/amqp/v2/go.sum
  vendor/github.com/cloudevents/sdk-go/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/v2/go.sum
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/gorilla/mux/go.mod
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/redhat-cne/rest-api/go.mod
  vendor/github.com/redhat-cne/rest-api/go.sum
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/valyala/fasthttp/go.mod
  vendor/github.com/valyala/fasthttp/go.sum
  vendor/go.uber.org/atomic/go.mod
  vendor/go.uber.org/atomic/go.sum
  vendor/go.uber.org/multierr/go.mod
  vendor/go.uber.org/multierr/go.sum
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/golang.org/x/lint/go.mod
  vendor/golang.org/x/lint/go.sum
  vendor/golang.org/x/xerrors/go.mod
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#81 Fixed get status not picking proper master interface
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm

#82 Consolidate Cloud Native Events schema
  README.md
  cmd/main.go
  examples/consumer/main.go
  examples/manifests/consumer.yaml
  examples/producer/main.go
  go.mod
  go.sum
  pkg/restclient/client.go
  plugins/mock/mock_plugin.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/stats/stats.go
  vendor/github.com/redhat-cne/rest-api/README.md
  vendor/github.com/redhat-cne/rest-api/pkg/localmetrics/localmetrics.go
  vendor/github.com/redhat-cne/rest-api/routes.go
  vendor/github.com/redhat-cne/rest-api/server.go
  vendor/github.com/redhat-cne/rest-api/swagger.json
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/types.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_interface.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_marshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/source.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/syncstate.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/types.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/event.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/event_marshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/event_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/types.go
  vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event.go
  vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event_ce.go
  vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event_interace.go
  vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event_reader.go
  vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event_writer.go
  vendor/github.com/redhat-cne/sdk-go/v1/event/event.go
  vendor/github.com/redhat-cne/sdk-go/v1/hwevent/docs.go
  vendor/github.com/redhat-cne/sdk-go/v1/hwevent/event.go
  vendor/modules.txt
Labels: approved
