Repository redhat-cne/cloud-event-proxy, pull requests merged in 2022-02, with the labels that each got.

#90 Add timeout to CI golangci-lint
  .github/workflows/main.yaml
Labels: approved, lgtm

#91 Add Dockerfile.dev for quay.io build triggers
  Dockerfile.dev
  examples/consumer.Dockerfile.dev
Labels: approved, lgtm

#94 Bug 2047308:Remove metrics and events for master port offsets
  Makefile
  docs/development.md
  examples/consumer.Dockerfile
  examples/consumer.Dockerfile.local
  examples/consumer/deployment/deployment.yaml
  examples/consumer/deployment/namespace.yaml
  examples/consumer/deployment/roles.yaml
  examples/consumer/deployment/sa.yaml
  examples/consumer/deployment/service.yaml
  examples/manifests/consumer.yaml
  examples/manifests/kustomization.yaml
  examples/manifests/namespace.yaml
  examples/manifests/roles.yaml
  examples/manifests/service-account.yaml
  examples/manifests/service.yaml
  hack/build-example-image.sh
  hack/common/cne.sh
  hack/common/common.sh
  hack/common/consumer.sh
  hack/deploy_test.sh
  plugins/ptp_operator/_testprofile/section
  plugins/ptp_operator/_testprofile/single
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/config/config_test.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/stats/stats.go
  test/utils/consts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#95 CNF-4018 Enable Flexible Registration for Multiple PTP Events clock-class-change,status and os-sync
  docs/development.md
  examples/consumer/main.go
  hack/common/cne.sh
  hack/common/common.sh
  hack/common/consumer.sh
  hack/deploy_test.sh
  plugins/mock/mock_plugin.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  plugins/ptp_operator/socket/socket_test.go
  plugins/ptp_operator/types/types.go
Labels: approved, lgtm

#97 Revert "CNF-4018 Enable Flexible Registration for Multiple PTP Events clock-class-change,status and os-sync"
  docs/development.md
  examples/consumer/main.go
  hack/common/cne.sh
  hack/common/common.sh
  hack/common/consumer.sh
  hack/deploy_test.sh
  plugins/mock/mock_plugin.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  plugins/ptp_operator/socket/socket_test.go
  plugins/ptp_operator/types/types.go
Labels: approved

#98 CNF-4018 Enable Flexible Registration for Multiple PTP Events clock-class-change,status and os-sync
  docs/development.md
  examples/consumer/main.go
  hack/common/cne.sh
  hack/common/common.sh
  hack/common/consumer.sh
  hack/deploy_test.sh
  plugins/mock/mock_plugin.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  plugins/ptp_operator/socket/socket_test.go
  plugins/ptp_operator/types/types.go
Labels: approved, lgtm
