Repository redhat-cne/cloud-event-proxy, pull requests merged in 2022-11, with the labels that each got.

#146 update base image in Dockerfile.dev
  Dockerfile.dev
  examples/consumer.Dockerfile.dev
Labels: approved, lgtm

#147 [release-4.11] Bug OCPBUGS-3295: Event Pull Status Notification GET Method not working as per o-Ran spec
  .gitignore
  cmd/main.go
  examples/consumer.Dockerfile
  examples/consumer.Dockerfile.local
  examples/consumer/deployment/deployment.yaml
  examples/consumer/main.go
  examples/manifests/consumer.yaml
  examples/manifests/kustomization.yaml
  go.mod
  go.sum
  hack/common/cne.sh
  hack/common/consumer.sh
  hack/deploy_test.sh
  pkg/common/common.go
  pkg/restclient/client.go
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig_test.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  plugins/ptp_operator/socket/socket_test.go
  plugins/ptp_operator/stats/stats.go
  test/cne/cne.go
  vendor/github.com/redhat-cne/rest-api/routes.go
  vendor/github.com/redhat-cne/rest-api/server.go
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/data.go
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/types.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
  vendor/github.com/redhat-cne/sdk-go/v1/pubsub/pubsub.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug

#148 Bug OCPBUGS-3296: PTP Event (AMQ) : Failed to get GetCurrentState for Events Clock Class Change
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug
