Repository redhat-cne/cloud-event-proxy, pull requests merged in 2022-05, with the labels that each got.

#117 Upgrade to v3 checkout action
  .github/workflows/main.yaml
Labels: approved, lgtm, needs-ok-to-test

#120 Bug 2090774: Add Readme to plugin folder
  README.md
  plugins/README.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#121 Bug 2091106: Update gopkg.in/yaml.v3 to v3.0.0 for security fix
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium
