Repository redhat-cne/cloud-event-proxy, pull requests merged in 2022-12, with the labels that each got.

#157 Fix amq router race condition: update vendors only
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
  vendor/modules.txt
Labels: approved, lgtm

#160 4.10 Fix amq router race condition: update vendors only
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
  vendor/modules.txt
Labels: approved, lgtm

#158 update rest-api version
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#159 4.11 Fix amq router race condition: update vendors only
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
  vendor/modules.txt
Labels: approved, lgtm

#162 Bug OCPBUGS-3350: Fix amq router race condition: update vendor only
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#163 Bug OCPBUGS-4953: PTP events - error message on even log needs to be remove
  plugins/ptp_operator/metrics/logparser.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-low

#165 Bug OCPBUGS-4961: Update vendor files for amqp resource leak fix
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#166 [release-4.12] Bug OCPBUGS-4255: Update vendor files for amqp resource leak fix
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#168 OCPBUGS-3667: Fix CLOCK_REALTIME going to HOLDOVER in metrics
  plugins/ptp_operator/metrics/ptp4lParse.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug

#170 OCPBUGS-3667: Fix CLOCK_REALTIME going to HOLDOVER in metrics
  plugins/ptp_operator/metrics/ptp4lParse.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug
