Repository redhat-cne/cloud-event-proxy, pull requests merged in 2023-01, with the labels that each got.

#172 OCPBUGS-5290: [release-4.11] Fix CLOCK_REALTIME going to HOLDOVER in metrics
  .golangci.yaml
  Makefile
  cmd/main.go
  examples/producer/main.go
  hack/gofmt.sh
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/stats/stats.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug

#167 [release-4.11] Bug OCPBUGS-4964: Update vendor files for amqp resource leak fix
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#173 update sdk-go model for increasing amq timeout
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
  vendor/modules.txt
Labels: approved, lgtm

#177 Bug OCPBUGS-5293: Dual Nic with single phc2sys throws nil pointer exception.
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#180 BUG OCPBUGS-5377: Fix channel staying in close state
  plugins/ptp_operator/metrics/manager.go
Labels: approved, bugzilla/valid-bug, jira/valid-bug

#183 BUG OCPBUGS-5377: Fix channel staying in close state
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/ptp4lParse.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#182 Remove duplicate logs when slave interface down
  plugins/ptp_operator/metrics/ptp4lParse.go
Labels: approved, lgtm

#186 Add metrics and events for ts2phc
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/ptp4lParse.go
Labels: approved, lgtm

#179 OCPBUGS-5357: [release-4.11] Dual Nic with single phc2sys throws nil pointer exception. n sending events
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#187 Amq connection configurable timeout and nohup
  cmd/main.go
  cmd/main_test.go
  go.sum
  pkg/plugins/handler.go
  pkg/plugins/handler_test.go
  plugins/amqp/amqp_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
Labels: approved, lgtm

#189 [release-4.12] BUG OCPBUGS-5526: Amq connection configurable timeout and nohup
  cmd/main.go
  cmd/main_test.go
  go.mod
  go.sum
  pkg/plugins/handler.go
  pkg/plugins/handler_test.go
  plugins/amqp/amqp_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#188 update sdk-go, rest-api versions for amq timeout
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved

#190 Update golang.org/x/net for CVE-2022-41717
  go.mod
  go.sum
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/static_table.go
  vendor/golang.org/x/net/http2/hpack/tables.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/modules.txt
Labels: approved, lgtm
