Repository redhat-cne/cloud-event-proxy, pull requests merged in 2023-04, with the labels that each got.

#233 OCPBUGS-11233: PTP - When GM and downstream slaves are configured on same server, ptp metrics show slaves as FREERUN
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#241 Install ginkgo
  .gitignore
  hack/run-functests.sh
Labels: approved, lgtm

#244 OCPBUGS-8249: Backport HTTP support fixes to 4.12 with nodename replaced
  cmd/main.go
  examples/consumer/main.go
  pkg/common/common.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#235 Update consumer deployment and README
  Dockerfile.dev
  README.md
  examples/consumer/deployment/deployment.yaml
  examples/consumer/deployment/roles.yaml
  examples/consumer/deployment/sa.yaml
  examples/consumer/deployment/service.yaml
  examples/manifests/kustomization.yaml
Labels: approved, lgtm

#246 [release-4.12] OCPBUGS-12361: PTP metrics - Unexpected metrics for old phc2sys appears in metrics after modify ptpconfigs
  cmd/main.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/registry.go
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate
