Repository redhat-cne/cloud-event-proxy, pull requests merged in 2023-02, with the labels that each got.

#191 [release-4.11] Bug OCPBUGS-4754: Amq connection configurable timeout and nohup
  .golangci.yaml
  cmd/main.go
  cmd/main_test.go
  go.mod
  go.sum
  pkg/plugins/handler.go
  pkg/plugins/handler_test.go
  plugins/amqp/amqp_plugin.go
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#193 fix ts2phc events and metrics
  cmd/main.go
  examples/consumer/deployment/deployment.yaml
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/ptp4lParse.go
Labels: approved, lgtm

#192 [release-4.10] Bug OCPBUGS-4755: Amq connection configurable timeout and nohup
  cmd/main.go
  cmd/main_test.go
  go.mod
  go.sum
  pkg/plugins/handler.go
  pkg/plugins/handler_test.go
  plugins/amqp/amqp_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#195 Add multi node support for http
  cmd/main.go
  pkg/common/common.go
Labels: approved, lgtm

#194 Bug OCPBUGS-2832: update sdk-go for http restart fix
  Makefile
  go.mod
  go.sum
  vendor/github.com/redhat-cne/rest-api/Makefile
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/pipeline.go
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/types.go
  vendor/github.com/redhat-cne/sdk-go/pkg/errorhandler/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/errorhandler/errorhandler.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_writer.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/interface.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
  vendor/github.com/redhat-cne/sdk-go/pkg/types/value.go
  vendor/github.com/redhat-cne/sdk-go/pkg/util/wait/wait.go
  vendor/github.com/redhat-cne/sdk-go/v1/http/http.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#197 BUG OCPBUGS-7441: Match the O-RAN specification for the ocloudNotifications URI
  README.md
  cmd/main.go
  cmd/main_test.go
  examples/consumer/deployment/deployment.yaml
  examples/consumer/main.go
  examples/manifests/consumer.yaml
  examples/producer/main.go
  hack/common/consumer.sh
  plugins/README.md
  test/cne/cne.go
Labels: approved, lgtm, ok-to-test, jira/invalid-bug, jira/valid-reference, jira/severity-moderate

#196 doc update: configure persistent storage for event producer
  README.md
Labels: approved, lgtm

#199 BUG OCPBUGS-5465: Fix SLAVE port going to master or listening state
  Makefile
  go.mod
  go.sum
  plugins/README.md
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/types/types.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#201 patch LISTENING string
  plugins/ptp_operator/metrics/registry.go
  plugins/ptp_operator/types/types.go
Labels: approved

#204 update sdk-go for Redfish Event Oem field fix
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/event_marshal.go
  vendor/modules.txt
Labels: approved, lgtm

#205 BUG OCPBUGS-7826: Add multi node support for consumer to identify publishers
  cmd/main.go
  examples/manifests/consumer.yaml
  pkg/common/common.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#209 Bug OCPBUGS-7831: Fix extra metrics
  plugins/ptp_operator/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#210 OCPBUGS-7997: [release-4.10] Fix clock realtime staying in locked when slave at fault
  Makefile
  pkg/restclient/client.go
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
  plugins/ptp_operator/stats/stats.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#211 OCPBUGS-7811: remove ptp process metrics when ptpcfig is deleted
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/registry.go
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#213 [release-4.11] Bug OCPBUGS-8039: Match the O-RAN spec for ocloudNotifications URI
  README.md
  cmd/main.go
  cmd/main_test.go
  examples/consumer/deployment/deployment.yaml
  examples/consumer/main.go
  examples/manifests/consumer.yaml
  examples/producer/main.go
  hack/common/consumer.sh
  plugins/README.md
  test/cne/cne.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate
