Repository redhat-cne/cloud-event-proxy, pull requests merged in 2023-03, with the labels that each got.

#214 [release-4.10] Bug OCPBUGS-8042: Match the O-RAN spec for ocloudNotifications URI
  README.md
  cmd/main.go
  cmd/main_test.go
  examples/consumer/deployment/deployment.yaml
  examples/consumer/main.go
  examples/manifests/consumer.yaml
  examples/producer/main.go
  hack/common/consumer.sh
  pkg/localmetrics/localmetrics.go
  plugins/README.md
  plugins/ptp_operator/ptp4lconf/ptp4lConfig_test.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  plugins/ptp_operator/socket/socket.go
  plugins/ptp_operator/types/types.go
  test/cne/cne.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#212 OCPBUGS-7808: Remove ptp metrics for masterclock on delete of ptpconfig
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#215 OCPBUGS-8003: Fix lost client subscription clean up and add validation
  cmd/main.go
  docs/metrics.md
  examples/manifests/consumer.yaml
  go.mod
  go.sum
  plugins/README.md
  plugins/ptp_operator/config/config.go
  vendor/github.com/redhat-cne/rest-api/routes.go
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/data.go
  vendor/github.com/redhat-cne/sdk-go/pkg/localmetrics/localmetrics.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/github.com/redhat-cne/sdk-go/pkg/store/store.go
  vendor/github.com/redhat-cne/sdk-go/pkg/store/subscriber/subscriber.go
  vendor/github.com/redhat-cne/sdk-go/pkg/subscriber/subscriber.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#216 Add example to use event subscription without using side car
  examples/consumer/main.go
  examples/simplehttp/common/currentstate.go
  examples/simplehttp/common/httpclient.go
  examples/simplehttp/common/subscribe.go
  examples/simplehttp/external-service.yaml
  examples/simplehttp/main.go
Labels: approved, lgtm

#200 [release-4.12] OCPBUGS-7561: Fix SLAVE port going to master or listening state
  Makefile
  cmd/main.go
  go.mod
  go.sum
  pkg/common/common.go
  plugins/README.md
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/metrics/registry.go
  plugins/ptp_operator/types/types.go
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/pipeline.go
  vendor/github.com/redhat-cne/sdk-go/pkg/channel/types.go
  vendor/github.com/redhat-cne/sdk-go/pkg/errorhandler/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/errorhandler/errorhandler.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_writer.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/interface.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
  vendor/github.com/redhat-cne/sdk-go/pkg/types/value.go
  vendor/github.com/redhat-cne/sdk-go/pkg/util/wait/wait.go
  vendor/github.com/redhat-cne/sdk-go/v1/http/http.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference

#217 OCPBUGS-7974: PTP BC: an unnecessary openshift_ptp_clock_state metric is shown
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/metrics/registry.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#219 Fix simplehttp to read events posted from ptp
  examples/simplehttp/common/currentstate.go
  examples/simplehttp/common/httpclient.go
  examples/simplehttp/common/report.go
  examples/simplehttp/common/server.go
  examples/simplehttp/common/subscribe.go
  examples/simplehttp/external-service.yaml
  examples/simplehttp/main.go
  examples/simplehttp/utils/response.go
  go.mod
Labels: approved, lgtm

#220 OCPBUGS-8415: Client does not recovered after it has been marked for delete
  cmd/main.go
  examples/simplehttp/external-service.yaml
  examples/simplehttp/main.go
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#202 [release-4.11] OCPBUGS-7562: Fix SLAVE port going to master/listening/uncalibrated/faulty
  plugins/README.md
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/metrics/registry.go
  plugins/ptp_operator/types/types.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#221 OCPBUGS-8521: [release-4.13] Client does not recovered after it has been marked for delete
  cmd/main.go
  examples/simplehttp/common/currentstate.go
  examples/simplehttp/common/httpclient.go
  examples/simplehttp/common/report.go
  examples/simplehttp/common/server.go
  examples/simplehttp/common/subscribe.go
  examples/simplehttp/external-service.yaml
  examples/simplehttp/main.go
  examples/simplehttp/utils/response.go
  go.mod
  go.sum
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/metrics/registry.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#223 OCPBUGS-8714: With GM config, phc2sys clock lock state is shown as FREERUN in ptp metrics while it should be LOCKED
  examples/simplehttp/common/httpclient.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/ptp4lParse.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#225 [release-4.10] OCPBUGS-791: PTP events - error message on event log needs to be remove
  plugins/ptp_operator/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#229 OCPBUGS-10297: Context Deadline exceeded when PTP service is disabled from the switch
  plugins/ptp_operator/metrics/logparser.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#228 [release-4.13] OCPBUGS-5465: Context Deadline exceeded when PTP service is disabled from the switch
  plugins/ptp_operator/metrics/logparser.go
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference

#227 [release-4.12] OCPBUGS-7561: Context Deadline exceeded when PTP service is disabled from the switch
  plugins/ptp_operator/metrics/logparser.go
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference

#226 [release-4.11] OCPBUGS-7562: Context Deadline exceeded when PTP service is disabled from the switch
  plugins/ptp_operator/metrics/logparser.go
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference

#203 [release-4.10] OCPBUGS-7721: Fix SLAVE port going to master/listening/uncalibrated/faulty
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/types/types.go
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference

#230 [release-4.11] Bug OCPBUGS-6580: PTP events - error log isn't clear and nil appears on the result
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference
