Repository redhat-cne/cloud-event-proxy, pull requests merged in 2024-12, with the labels that each got.

#371 OCPBUGS-44954: PTP operator Event Notification API breaking change within 4.16 release
  examples/consumer/main.go
  go.mod
  go.sum
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/resource.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#373 [release-4.16] OCPBUGS-44900: PTP operator Event Notification API breaking change within 4.16 release
  examples/consumer/main.go
  go.mod
  go.sum
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/resource.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference

#378 OCPBUGS-46150: fix subscription for multiple clients
  go.mod
  go.sum
  vendor/github.com/redhat-cne/rest-api/.gitignore
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#380 OCPBUGS-45866 : Fix GM State Transition Event Generation
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
Labels: approved, lgtm

#385 update owners
  OWNERS_ALIASES
Labels: approved

#391 OCPBUGS-46627: add checking of mandatory fields in pubsub
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go
  vendor/modules.txt
Labels: approved, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#382 OCPBUGS-47515: [release-4.17] Fix GM State Transition Event Generation
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#383 OCPBUGS-47518: [release-4.16] Fix GM State Transition Event Generation
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#384 OCPBUGS-47519: [release-4.15] Fix GM State Transition Event Generation
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, backport-risk-assessed

#395 OCPBUGS-47709: [release-4.17] fix backport mistake
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/metrics_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, backport-risk-assessed
