Repository redhat-cne/cloud-event-proxy, pull requests merged in 2024-06, with the labels that each got.

#316 CNF-12095: add api-version
  cmd/main.go
Labels: approved, lgtm, jira/valid-reference

#292 Log decoded received event
  examples/consumer/main.go
Labels: approved, lgtm

#318 [release-4.15] OCPBUGS-35888: GNSS EVENT state is not following O-Ran spec defined values
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/stats/stats.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#319 [release-4.14] OCPBUGS-35889: GNSS EVENT state is not following O-Ran spec defined values
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/config/config_test.go
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/stats/stats.go
Labels: approved, lgtm, jira/invalid-bug, jira/valid-reference
