Repository redhat-cne/cloud-event-proxy, pull requests merged in 2024-05, with the labels that each got.

#307 Fix consumer image and e2e-aws test
  examples/consumer.Dockerfile
  examples/consumer.Dockerfile.dev
  examples/consumer/deployment/namespace.yaml
  examples/consumer/main.go
  examples/manifests/namespace.yaml
  hack/common/common.sh
  hack/common/consumer.sh
  hack/common/router.sh
  hack/deploy_test.sh
  test/cne/cne.go
Labels: approved, lgtm

#308 fix dev Dockerfiles
  Dockerfile.dev
  examples/consumer.Dockerfile.dev
Labels: approved

#309 [release-4.15] Fix consumer and e2e aws test
  Dockerfile.dev
  examples/consumer.Dockerfile
  examples/consumer.Dockerfile.dev
  examples/consumer/deployment/namespace.yaml
  examples/consumer/main.go
  examples/manifests/consumer.yaml
  examples/manifests/namespace.yaml
  hack/common/common.sh
  hack/common/consumer.sh
  hack/common/router.sh
  hack/deploy_test.sh
  pkg/common/common.go
  test/cne/cne.go
Labels: approved, lgtm

#306 [release-4.15] OCPBUGS-32305: fix missing openshift_ptp_process_status metric after initial installation
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/config/config_test.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/registry.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/stats/stats.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#310 update kube-rbac-proxy image in consumer pod
  examples/manifests/consumer.yaml
Labels: approved, lgtm

#312 OCPBUGS-31575: GNSS EVENT state is not following O-Ran spec defined values
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/stats/stats.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
