Repository redhat-cne/cloud-event-proxy, pull requests merged in 2024-07, with the labels that each got.

#315 CNF-12095: O-RAN V3 Rest Api: Event Subscription
  Makefile
  README.md
  cmd/main.go
  cmd/main_test.go
  examples/consumer.Dockerfile
  examples/consumer.Dockerfile.dev
  examples/consumer/main.go
  examples/manifests/v2/consumer.yaml
  examples/manifests/v2/kustomization.yaml
  examples/manifests/v2/namespace.yaml
  examples/manifests/v2/roles.yaml
  examples/manifests/v2/service-account.yaml
  examples/manifests/v2/service.yaml
  examples/producer/main.go
  go.mod
  go.sum
  pkg/common/common.go
  pkg/plugins/handler_test.go
  pkg/restclient/client.go
  pkg/storage/kubernetes/client.go
  plugins/mock/mock_plugin.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/rest-api/pkg/restclient/client.go
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/rest-api/v2/swagger.json
  vendor/github.com/redhat-cne/sdk-go/pkg/common/common.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_marshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_interface.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_marshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_reader.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_writer.go
  vendor/github.com/redhat-cne/sdk-go/pkg/store/store.go
  vendor/github.com/redhat-cne/sdk-go/v1/pubsub/pubsub.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, jira/valid-reference

#321 OCPBUGS-36496: GM clock_state stuck in freerun
  plugins/ptp_operator/metrics/metrics.go
Labels: approved, lgtm, jira/invalid-bug, jira/valid-reference, jira/severity-critical

#320 CNF-13067: O-RAN V3 Rest Api: Status Notification
  cmd/main.go
  examples/consumer/main.go
  examples/producer/main.go
  examples/simplehttp/common/subscribe.go
  go.mod
  go.sum
  pkg/common/common.go
  pkg/storage/kubernetes/client.go
  plugins/ptp_operator/metrics/manager.go
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/sdk-go/pkg/common/common.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/resource.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/syncstate.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/types.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/subscriber/subscriber.go
  vendor/github.com/redhat-cne/sdk-go/pkg/subscriber/subscriber_writer.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, jira/valid-reference

#323 Set Event Source according to O-RAN Spec
  examples/manifests/v2/kustomization.yaml
  go.mod
  go.sum
  pkg/common/common.go
  plugins/mock/mock_plugin.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
  vendor/modules.txt
Labels: approved, lgtm

#327 OCPBUGS-35587: T-GM - ts2phc process restart doesn't update PTP syncState when the process recovered
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/stats/stats.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#326 OCPBUGS-33594: implement /sync/sync-status/sync-state
  examples/consumer/main.go
  go.mod
  go.sum
  pkg/common/common.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
