Repository redhat-cne/cloud-event-proxy, pull requests merged in 2024-09, with the labels that each got.

#342 [release-4.16] OCPBUGS-38639: implement over all sync-status
  examples/consumer/main.go
  pkg/common/common.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#348 update sdk-go rest-api version and dev dockerfile
  Dockerfile
  Dockerfile.dev
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/pkg/subscriber/subscriber_writer.go
  vendor/modules.txt
Labels: approved, lgtm

#352 OCPBUGS-41636: Maintain HOLDOVER for BC/OC when faulty interface returns until Clock is locked
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/manager_test.go
  plugins/ptp_operator/metrics/metrics_test.go
  plugins/ptp_operator/metrics/ptp4lParse.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#351 [release-4.14] OCPBUGS-41353: implement over all sync-status
  examples/consumer/main.go
  pkg/common/common.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
Labels: approved, lgtm, jira/invalid-bug, jira/valid-reference

#353 OCPBUGS-39218: fix double / in ResourceAddress
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#354 [release-4.16] OCPBUGS-41886: fix double / in ResourceAddress
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
Labels: approved, lgtm, jira/invalid-bug, jira/valid-reference, jira/severity-moderate

#358 OCPBUGS-19838:PTP HW Clock Class after disabling NMEA sentences - Handle T-GM holdover
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/metrics.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
