Repository redhat-cne/cloud-event-proxy, pull requests merged in 2024-08, with the labels that each got.

#331 Enable synce metrics and events
  .golangci.yaml
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/event/event.go
  plugins/ptp_operator/metrics/logData.go
  plugins/ptp_operator/metrics/logData_test.go
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/registry.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  plugins/ptp_operator/stats/stats.go
Labels: approved, lgtm

#333 Fix synce events for getCurrentState and regular event
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm

#329 OCPBUGS-33594: trigger overall sync-state events
  go.mod
  go.sum
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#334 fix metrics help and value for synce
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/registry.go
Labels: approved, lgtm

#336 OCPBUGS-38216: fix subscription recovery from reboot
  go.mod
  go.sum
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#337 [release-4.14] fix e2e-aws
  hack/deploy_test.sh
Labels: approved, lgtm

#335 v2 consumer app manifests cleanup
  examples/manifests/v2/consumer.yaml
  examples/manifests/v2/kustomization.yaml
  examples/manifests/v2/roles.yaml
  examples/manifests/v2/service-account.yaml
  examples/manifests/v2/service.yaml
Labels: approved, lgtm

#338 OCPBUGS-35799: OCPBUGS-38284: clean up subscriptions when lost connection to consumer
  cmd/main.go
  go.mod
  go.sum
  pkg/restclient/client.go
  pkg/storage/kubernetes/client.go
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate
