Repository redhat-cne/cloud-event-proxy, pull requests merged in 2025-04, with the labels that each got.

#459 OCPBUGS-54543: Data race in Server.status access causes instability in cloud-event-proxy
  go.mod
  go.sum
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#461 update getOverallState
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm

#460 Update Github action runners
  .github/workflows/main.yaml
Labels: approved, lgtm

#458 OCPBUGS-53247: CLOCK_REALTIME state reports 1 (locked) when both active and inactive interfaces are down in BC/OC HA environment
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/manager_test.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#466 fix lint for older releases
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm

#469 OCPBUGS-45680: add error handling in configmap and consumer app subscription
  Makefile
  cmd/main.go
  examples/consumer/main.go
  pkg/restclient/client.go
  pkg/storage/kubernetes/client.go
  pkg/storage/kubernetes/client_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#472 OCPBUGS-45680: fix get CurrentState
  pkg/restclient/client.go
Labels: approved, jira/severity-important, jira/invalid-bug, jira/valid-reference

#470 OCPBUGS-54984: Update Sync State Logic for Downstream Slave When All HA Interfaces Are Down
  Makefile
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/metrics_test.go
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#475 [release-4.18] Update Github action runner ubuntu-20.04->ubuntu-24.04
  .github/workflows/main.yaml
Labels: approved

#463 [release-4.17] OCPBUGS-54964: handle concurrent map read and write for stats object
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/manager_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, backport-risk-assessed

#462 parse BC holdover
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/metrics/ptp4lParse.go
Labels: approved, lgtm

#483 [release-4.15] fix ut and lint
  .github/workflows/main.yaml
  .golangci.yaml
  Makefile
  examples/consumer/main.go
  examples/producer/main.go
  examples/simplehttp/common/httpclient.go
  examples/simplehttp/common/server.go
  examples/simplehttp/main.go
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm

#488 OCPBUGS-55391: reduce event logs
  go.mod
  go.sum
  pkg/common/common.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#489 Update k8s client test to v2
  examples/consumer/main.go
  pkg/common/common.go
  pkg/storage/kubernetes/client_test.go
Labels: approved, lgtm
