Repository redhat-cne/cloud-event-proxy, pull requests merged in 2025-03, with the labels that each got.

#421 update e2e to run in v2
  hack/common/cne.sh
  hack/common/consumer.sh
  hack/run-functests.sh
  plugins/mock/mock_plugin.go
  test/cne/cne.go
Labels: approved, lgtm

#422 Fix consumer subscription race condition
  examples/consumer/main.go
  hack/common/cne.sh
Labels: approved, lgtm

#423 Fix e2e test intermittent issues
  examples/consumer/main.go
  test/cne/cne.go
Labels: approved, lgtm

#424 Update main.go to drop support for API v1
  cmd/main.go
  hack/common/cne.sh
Labels: approved, lgtm

#425 Fix e2e test checking for pods
  test/cne/cne.go
  test/utils/pods/pods.go
Labels: approved, lgtm

#429 fix consumer build
  Dockerfile.dev
  Makefile
  examples/consumer.Dockerfile
  examples/consumer.Dockerfile.dev
Labels: approved, lgtm

#432 upgrade to go 1.23 and update rest-api
  .github/workflows/main.yaml
  go.mod
  go.sum
  vendor/github.com/redhat-cne/rest-api/.gitignore
  vendor/github.com/redhat-cne/rest-api/.golangci.yaml
  vendor/github.com/redhat-cne/rest-api/README.md
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/rest-api/v2/swagger.json
  vendor/github.com/redhat-cne/rest-api/v2/tags.json
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
  vendor/modules.txt
Labels: approved, lgtm

#431 Update image base in consumer Dockerfile
  Makefile
  examples/consumer.Dockerfile
  examples/consumer.Dockerfile.dev
Labels: approved, lgtm

#439 [release-4.18] Update consumer Dockerfile
  Dockerfile.dev
  Makefile
  examples/consumer.Dockerfile
  examples/consumer.Dockerfile.dev
Labels: approved, lgtm

#440 Add missing transitions to FOLLOWING
  plugins/ptp_operator/metrics/logparser.go
Labels: approved, lgtm

#441 CNF-16979: Remove Event API v1 support from consumer app
  Makefile
  examples/Dockerfile.tmp
  examples/consumer/main.go
  examples/manifests/configmap.yaml
  examples/manifests/consumer.yaml
  examples/manifests/kube-dns/kube-dns-cm.yaml
  examples/manifests/kube-dns/kube-dns-controller.yaml
  examples/manifests/kube-dns/kube-dns-svc.yaml
  examples/manifests/kube-dns/kustomization.yaml
  examples/manifests/kustomization.yaml
  examples/manifests/roles.yaml
  examples/manifests/service-account.yaml
  examples/manifests/service.yaml
  examples/manifests/v2/consumer.yaml
  examples/manifests/v2/kustomization.yaml
  examples/manifests/v2/namespace.yaml
  examples/manifests/v2/service-account.yaml
  examples/manifests/v2/service.yaml
  hack/common/consumer.sh
  plugins/mock/mock_plugin.go
Labels: approved, lgtm, jira/valid-reference

#442 fix consumer manifests
  examples/manifests/kustomization.yaml
Labels: approved, lgtm

#443 OCPBUGS-54160: Handle concurrent map read and write for stats object
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/manager_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#444 Add commit log at build time
  Makefile
  cmd/main.go
Labels: approved, lgtm

#446 [WIP] add multi-arch build consumer image
  .github/workflows/build.yaml
Labels: approved, do-not-merge/work-in-progress

#447 debug
  .github/workflows/build.yaml
Labels: approved

#448 Consumer image arm
  .github/workflows/build.yaml
Labels: approved

#449 disable attestations
  .github/workflows/build.yaml
Labels: approved

#450 disable attestations
  .github/workflows/build.yaml
Labels: approved

#451 disable attestations
  .github/workflows/build.yaml
Labels: approved

#452 update2
  .github/workflows/build.yaml
Labels: approved

#453 enable multi-arch consumer image
  .github/workflows/build.yaml
Labels: approved, lgtm

#454 CNF-17240: Change consumer image label release-4.18 to 4.18
  .github/workflows/build.yaml
  Makefile
Labels: approved, lgtm, jira/valid-reference

#457 remove temp file examples/Dockerfile.tmp
  examples/Dockerfile.tmp
Labels: approved
