Repository redhat-cne/cloud-event-proxy, pull requests merged in 2025-05, with the labels that each got.

#495 Extract listening state when transitioning from faulty
  plugins/ptp_operator/metrics/logparser.go
Labels: approved, lgtm

#497 fix e2e-aws intermittent failure
  test/cne/cne.go
Labels: approved, lgtm

#502 Properly handle dotted vlan tag in interface name
  plugins/ptp_operator/metrics/metrics.go
Labels: approved, lgtm

#503 OCPBUGS-56053: Suppress Error Logging for DPLL Phase Offset Calculation
  examples/consumer/main.go
  plugins/ptp_operator/metrics/logparser.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#506 [release-4.14] Fix lint 4.14
  .github/workflows/main.yaml
  .golangci.yaml
  Dockerfile.dev
  Makefile
  examples/consumer.Dockerfile
  examples/consumer.Dockerfile.dev
  examples/consumer/main.go
  examples/producer/main.go
  examples/simplehttp/common/httpclient.go
  examples/simplehttp/common/server.go
  examples/simplehttp/main.go
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved

#513 Replaces all aliasing lines with a common function
  plugins/ptp_operator/event/event.go
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
  plugins/ptp_operator/utils/utils.go
Labels: approved, lgtm

#516 [release-4.16] OCPBUGS-56273: reduce event logs
  go.mod
  go.sum
  test/cne/cne.go
  vendor/github.com/redhat-cne/rest-api/.gitignore
  vendor/github.com/redhat-cne/rest-api/.golangci.yaml
  vendor/github.com/redhat-cne/rest-api/README.md
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/rest-api/v2/swagger.json
  vendor/github.com/redhat-cne/rest-api/v2/tags.json
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#519 Add unit test for GetAlias
  plugins/ptp_operator/utils/utils_test.go
Labels: approved, lgtm

#517 [release-4.15] add error handling in configmap and consumer app subscription
  Makefile
  cmd/main.go
  examples/consumer/main.go
  examples/manifests/consumer.yaml
  pkg/common/common.go
  pkg/restclient/client.go
  pkg/storage/kubernetes/client.go
  pkg/storage/kubernetes/client_test.go
  plugins/ptp_operator/config/config.go
Labels: approved, lgtm

#521 Bump sdk-go and rest-api versions
  cmd/main_test.go
  go.mod
  go.sum
  pkg/common/common.go
  pkg/plugins/handler_test.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/rest-api/.gitignore
  vendor/github.com/redhat-cne/rest-api/.golangci.yaml
  vendor/github.com/redhat-cne/rest-api/.travis.yml
  vendor/github.com/redhat-cne/rest-api/CODE_OF_CONDUCT.md
  vendor/github.com/redhat-cne/rest-api/CONTRIBUTING.md
  vendor/github.com/redhat-cne/rest-api/Makefile
  vendor/github.com/redhat-cne/rest-api/README.md
  vendor/github.com/redhat-cne/rest-api/routes.go
  vendor/github.com/redhat-cne/rest-api/server.go
  vendor/github.com/redhat-cne/rest-api/swagger.json
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_interface.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_reader.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_writer.go
  vendor/github.com/redhat-cne/sdk-go/pkg/store/store.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, lgtm

#518 [release-4.19] OCPBUGS-56423: Replaces all aliasing lines with a common function
  plugins/ptp_operator/event/event.go
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/metrics.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
  plugins/ptp_operator/utils/utils.go
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference, backport-risk-assessed

#525 [release-4.14] OCPBUGS-56548: add error handling in configmap and consumer app subscription
  Makefile
  cmd/main.go
  examples/consumer/main.go
  examples/manifests/consumer.yaml
  pkg/common/common.go
  pkg/restclient/client.go
  pkg/storage/kubernetes/client.go
  pkg/storage/kubernetes/client_test.go
  plugins/ptp_operator/config/config.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
