Repository redhat-cne/cloud-event-proxy, pull requests merged in 2025-01, with the labels that each got.

#399 OCPBUGS-45308: Fix gm states 4.14
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/logparser_test.go
  plugins/ptp_operator/metrics/metrics_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical, backport-risk-assessed

#400 [release-4.17] OCPBUGS-47791: OCPBUGS-47792: update sdk-go and rest-api
  go.mod
  go.sum
  vendor/github.com/redhat-cne/rest-api/.gitignore
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#401 [release-4.16] OCPBUGS-47795: OCPBUGS-47793: update sdk-go and rest-api
  go.mod
  go.sum
  vendor/github.com/redhat-cne/rest-api/.gitignore
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, lgtm, jira/invalid-bug, jira/valid-reference, jira/severity-moderate
