Repository redhat-cne/cloud-event-proxy, pull requests merged in 2025-06, with the labels that each got.

#533 [ART-13123] append .0 to go.mod version
  go.mod
Labels: approved, ok-to-test, backport-risk-assessed

#539 fix SyncE events in onReceiveOverrideFn
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm

#515 [release-4.18] OCPBUGS-56272: ptp all sync-state event should be FREERUN. Instead sends event as LOCKED and resource address should be consistent
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/metrics/manager_test.go
  plugins/ptp_operator/metrics/metrics_test.go
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  plugins/ptp_operator/types/types.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, backport-risk-assessed
