Repository redhat-cne/cloud-event-proxy, pull requests merged in 2025-08, with the labels that each got.

#567 OCPBUGS-59969: Handle missing event data in getCurrentState with 404 response
  go.mod
  go.sum
  plugins/ptp_operator/ptp_operator_plugin.go
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/valid-reference, jira/severity-critical

#568 [release-4.19] Remove HTTP protocol and use new sdk-go
  Dockerfile.dlv
  Makefile
  README.md
  cmd/main.go
  cmd/main_test.go
  examples/consumer/main.go
  examples/producer/main.go
  examples/simplehttp/common/currentstate.go
  examples/simplehttp/common/httpclient.go
  examples/simplehttp/common/report.go
  examples/simplehttp/common/server.go
  examples/simplehttp/common/subscribe.go
  examples/simplehttp/external-service.yaml
  examples/simplehttp/main.go
  examples/simplehttp/utils/response.go
  go.mod
  go.sum
  pkg/common/common.go
  pkg/plugins/handler.go
  pkg/plugins/handler_test.go
  pkg/storage/kubernetes/client.go
  pkg/storage/kubernetes/client_test.go
  plugins/http/http_plugin.go
  plugins/mock/mock_plugin.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/ptp_operator_plugin_test.go
  vendor/github.com/redhat-cne/rest-api/.gitignore
  vendor/github.com/redhat-cne/rest-api/.golangci.yaml
  vendor/github.com/redhat-cne/rest-api/.travis.yml
  vendor/github.com/redhat-cne/rest-api/CODE_OF_CONDUCT.md
  vendor/github.com/redhat-cne/rest-api/CONTRIBUTING.md
  vendor/github.com/redhat-cne/rest-api/Makefile
  vendor/github.com/redhat-cne/rest-api/README.md
  vendor/github.com/redhat-cne/rest-api/routes.go
  vendor/github.com/redhat-cne/rest-api/server.go
  vendor/github.com/redhat-cne/rest-api/swagger.json
  vendor/github.com/redhat-cne/rest-api/v2/routes.go
  vendor/github.com/redhat-cne/rest-api/v2/server.go
  vendor/github.com/redhat-cne/sdk-go/pkg/common/common.go
  vendor/github.com/redhat-cne/sdk-go/pkg/errorhandler/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/errorhandler/errorhandler.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/doc.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/interface.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_interface.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_marshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_reader.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_writer.go
  vendor/github.com/redhat-cne/sdk-go/pkg/store/store.go
  vendor/github.com/redhat-cne/sdk-go/v1/http/http.go
  vendor/github.com/redhat-cne/sdk-go/v1/pubsub/pubsub.go
  vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
  vendor/modules.txt
Labels: approved, lgtm

#574 OCPBUGS-60261: Fix PTP interface role assignment and metrics generation on container restart [release-4.19]
  .golangci.yaml
  plugins/ptp_operator/config/config.go
  plugins/ptp_operator/metrics/manager.go
  plugins/ptp_operator/ptp_operator_plugin.go
Labels: approved, lgtm, jira/severity-important, jira/invalid-bug, jira/valid-reference, backport-risk-assessed

#579 OCPBUGS-60594: Update clock class help message
  plugins/ptp_operator/metrics/registry.go
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#578 [release-4.15] OCPBUGS-60622: Handle missing event data in getCurrentState with 400 response
  go.mod
  go.sum
  plugins/ptp_operator/ptp_operator_plugin.go
  vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical
