Repository redhat-cne/cloud-event-proxy, pull requests merged in 2025-02, with the labels that each got.

#404 Adding support for PTP configuration with only followers
  Dockerfile.dlv
  Makefile
  README.md
  cmd/main.go
  examples/consumer.Dockerfile.dlv
  plugins/ptp_operator/README.md
  plugins/ptp_operator/docs/bc.svg
  plugins/ptp_operator/docs/clock-states.svg
  plugins/ptp_operator/docs/configurations.md
  plugins/ptp_operator/docs/dual-follower-overview.svg
  plugins/ptp_operator/docs/dual-follower.svg
  plugins/ptp_operator/docs/dual-nic-bc.svg
  plugins/ptp_operator/docs/gnss.svg
  plugins/ptp_operator/docs/oc.svg
  plugins/ptp_operator/docs/port-states.svg
  plugins/ptp_operator/docs/tgm.svg
  plugins/ptp_operator/docs/timing-sw-overview.svg
  plugins/ptp_operator/metrics/logparser.go
  plugins/ptp_operator/metrics/metrics_test.go
  plugins/ptp_operator/metrics/ptp4lParse.go
  plugins/ptp_operator/metrics/registry.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
  plugins/ptp_operator/ptp4lconf/ptp4lConfig_test.go
  plugins/ptp_operator/ptp_operator_plugin.go
  plugins/ptp_operator/types/types.go
Labels: approved, lgtm

#415 update owners
  OWNERS_ALIASES
Labels: approved, lgtm, do-not-merge/invalid-owners-file

#416 [release-4.13] Fix e2e-aws
  hack/deploy_test.sh
Labels: approved

#417 [release-4.12] fix e2e-aws
  hack/deploy_test.sh
Labels: approved
